name: RunMetrics
on:
  # Schedule updates
  schedule: [{cron: "0 0 * * *"}]
  push: { branches: "main"} 
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
        # You'll need to setup a personal token in your secrets.
          token: ${{ secrets.METRICS_TOKEN }}
          user: yanevasquez
          template: terminal
          base: header, activity, community, repositories, metadata
          config_timezone: America/Fortaleza
          plugin_stars: yes
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 1000
          plugin_habits_languages_limit: 15
          plugin_habits_charts: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_limit: 20
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used